application: meme-ios-backend
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: templates/static
- url: /admin/.*
  script: main.py
  login: admin
  secure: always
- url: .*
  script: main.py